name: Hello World

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "Cluster target"
        required: true
        options:
          - ccd01devawx
          - ccd07-ibr-nucleus
          - ccd13cisawx
    
  push:
    branches: [master]

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
    - name: greetings
      run: echo "You have selected {{ inputs.cluster }}!"
