name: GitHub Action Workflow Practice
run-name: '${{ github.actor }} started the pipeline GitHub Action Workflow Practice'

on:
  workflow_dispatch:
    inputs:
      target:
        description: kuch info daal
        required: true

jobs:
  print-variable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install yq
      run: |
        if ! command -v yq &> /dev/null; then
            pip install yq
        fi

    - name: Print variable value
      run: |
        CONFIG_FILE=helloworld.txt
        testvariable=$(yq '.testvariable' $CONFIG_FILE)
        #echo "testvariable=$testvariable" >> $GITHUB_ENV
        echo "Value of variable $testvariable"
        #exit 1
  
  notify-job:
    needs: print-variable
    if : always()
    runs-on: ubuntu-latest

    steps:
    - name: Print Failed
      if: needs.print-variable.result=='failure'
      run: echo "Failed Job"

    - name: Print Success
      if: needs.print-variable.result=='success'
      run: echo "sab sahi hai ${{ inputs.target }}"
