name: GitHub Action Workflow Practice
run-name: '${{ github.actor }} started the pipeline'

on:
  workflow_dispatch

jobs:
  print-variable_value:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install yq
      run: |
        if ! command -v yq &> /dev/null; then
            pip install yq
        fi

    - name: Print variable value
      run: |
        CONFIG_FILE=helloworld.txt
        testvariable=$(yq '.testvariable' $CONFIG_FILE)
        echo "testvariable=$testvariable" >> $GITHUB_ENV
        echo "Value of variable $testvariable"

